import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import SearchBarComponent from "@/components/SearchBarComponent";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[var(--graybg)] `}
      >
        <SidebarProvider>
          {/* Main Layout */}
          <div className="flex h-screen w-screen">
            {/* Left Sidebar */}
            <div className="h-screen">
              <AppSidebar />
            </div>

            {/* Main Content */}
            <main className="flex flex-col p-5  overflow-auto scrollbar-hide">
              <div>
                <SearchBarComponent />
              </div>

              {/* Scrollable Content */}
              <div className="flex-1 overflow-auto scrollbar-hide">
                {children}
              </div>
            </main>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}